@startuml azure-ci-cd
hide footbox

!theme materia

collections "Source Code" as code
box "Continous Integration <&queue>"
[-> Build : trigger CI/CD pipeline
activate Build
Build -> Artifacts : create artifacts
deactivate Build
end box
box "Continous Delivery"
"Artifacts" -> "Artifacts Store" : store artifacts
end box
note over "Artifacts Store"
Artifacts can be anything produced by buld process, for example:
- binaries hosted in Azure Artifacts, Artifactory etc
- docker images hosted in Azure Container Registry
- else we want to release, like documents, etc
end note
box "Continous Deployment \n& Release"
"Artifacts Store" -> "Hosting Environment" : Deploy
"Hosting Environment" -> "Release" : use feature \ntoggles to control releases
end box
@enduml